name: ci-main
run-name: ci-main
on:
  workflow_dispatch:
  push:
  
jobs:

  anchore-scan:
    uses: ./.github/workflows/anchore-scan.yml
    if: github.ref == 'refs/heads/main'

  tag-container-push:
    uses: ./.github/workflows/tag-container-push.yml
    needs: [anchore-scan]
    if: github.ref == 'refs/heads/main'

