#
# This action does the following:
# 1) Creates a new release containing the repository source code, tagging the
#    release with an appropriate version number, and publishing it on the Github project
#    page
# 2) Build a container image, tagging the release with an appropriate version number,
#    and publishing it on the Github project page
#
# Notes:
# - The version number is incremented every release as described in
#   https://github.com/mathieudutour/github-tag-action. Note that by default semantic
#   version numbers are used and the patch number is incremented every release.
#   Moreover, in accordance with Angular conventional commits convention, the minor or
#   major number is incremented only upon detection of commits in the history with
#   certain formats. E.g. a commit beginning with 'feat:', signifying a new feature,
#   would result in the minor number being incremented. For details on the expected
#   format of commit messages in this regard see
#   https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular.
#

name: tag-container-push
run-name: tag-container-push


on:
  workflow_call:
  # ADDED FOR TESTING PURPOSES
  push:
  
jobs:
  tag-container-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Checkout the latest commit on the branch rather than not the commit which instigated the workflow. These are not the same if a bot has pushed a new commit to the branch during the workflow
          ref: ${{ github.ref }}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Setup docker auth
        run: |
          cat <<EOF > ~/.docker/config.json
          {
            "auths": {
              "ghcr.io": {
                "auth": "$(echo -n "$GIT_USERNAME:$GIT_PASSWORD" | base64 -w0)"
              }
            }
          }
          EOF
        env: # needed to authenticate to github and download the repo
          GIT_USERNAME: ${{ github.actor }}
          GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build API
        env:
          DOCKER_IMAGE_NAME: "ghcr.io/psdi-uk/data-transfer-container/data-transfer:${{ steps.tag_version.outputs.new_tag }}"
        run: |
          docker build -t $IMAGE_NAME .
          docker push $DOCKER_IMAGE_NAME
      - name: Install Apptainer
        run: |
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt install -y apptainer
          apptainer --version
      - name: Build Apptainer image from Docker image
        env: 
          APPTAINER_IMAGE_NAME: "ghcr.io/psdi-uk/data-transfer-container/data-transfer-sif:${{ steps.tag_version.outputs.new_tag }}"
        run: |
          docker images
          apptainer build container.sif docker-daemon://$DOCKER_IMAGE_NAME
          apptainer push container.sif oras://$APPTAINER_IMAGE_NAME